# Generated by Django 6.0.1 on 2026-03-08 14:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Black', 'Noir'), ('White', 'Blanc')], help_text='Color of the card', max_length=12, verbose_name='Colors')),
                ('value', models.PositiveSmallIntegerField(help_text='Value of the card', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valeur des Cartes',
                'verbose_name_plural': 'Valeurs des cartes',
                'unique_together': {('color', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Pseudo', max_length=30, verbose_name='Pseudos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Utilisateur', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_1', models.ForeignKey(help_text='Player One of the GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_one', to='blind_stack_app.player', verbose_name='Players')),
                ('player_2', models.ForeignKey(help_text='Player Two of the GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_two', to='blind_stack_app.player', verbose_name='Players')),
                ('player_3', models.ForeignKey(help_text='Player Three of the GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_three', to='blind_stack_app.player', verbose_name='Players')),
                ('player_4', models.ForeignKey(blank=True, help_text='Player Four of the GameRound', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_four', to='blind_stack_app.player', verbose_name='Players')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='Rank of the stack', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Ranks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_round', models.ForeignKey(help_text='GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='blind_stack_app.gameround', verbose_name='GameRounds')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_stack', models.PositiveSmallIntegerField(blank=True, help_text='Order of the Card in the Stack', null=True, verbose_name='Orders in Stack')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.ForeignKey(help_text='Cards of the GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='blind_stack_app.cardvalue', verbose_name='Cards')),
                ('game_round', models.ForeignKey(help_text='GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='blind_stack_app.gameround', verbose_name='GameRounds')),
                ('player', models.ForeignKey(blank=True, help_text='Players of the GameRound', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='blind_stack_app.player', verbose_name='Players')),
                ('stack', models.ForeignKey(blank=True, help_text='Players of the GameRound', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='blind_stack_app.stack', verbose_name='Stacks')),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cartes',
            },
        ),
    ]
