# Generated by Django 6.0.1 on 2026-02-17 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Black', 'Noir'), ('White', 'Blanc')], help_text='Color of the card', max_length=12, verbose_name='Colors')),
                ('value', models.PositiveSmallIntegerField(help_text='Value of the card', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Values')),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cartes',
                'unique_together': {('color', 'value')},
            },
        ),
    ]
