# Generated by Django 6.0.1 on 2026-03-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_stack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameround',
            options={'verbose_name': 'Partie de jeu', 'verbose_name_plural': 'Parties de jeu'},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name': 'Pile de carte', 'verbose_name_plural': 'Piles de cartes'},
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player_1', models.F('player_2')), _negated=True), models.Q(('player_1', models.F('player_3')), _negated=True), models.Q(('player_2', models.F('player_3')), _negated=True), models.Q(('player_4__isnull', True), models.Q(models.Q(('player_1', models.F('player_4')), _negated=True), models.Q(('player_2', models.F('player_4')), _negated=True), models.Q(('player_3', models.F('player_4')), _negated=True)), _connector='OR')), name='unique_players_in_game_round'),
        ),
    ]
