# Generated by Django 6.0.1 on 2026-03-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_stack_app', '0002_alter_gameround_options_alter_stack_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cardvalue',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 12)), name='check_card_value'),
        ),
    ]
