# Generated by Django 6.0.1 on 2026-03-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_stack_app', '0003_cardvalue_check_card_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='completed',
            field=models.BooleanField(default=False, help_text='The GameRound is completed ?', verbose_name='Completeds'),
        ),
    ]
