# Generated by Django 6.0.1 on 2026-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_stack_app', '0004_gameround_completed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stack',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1), ('rank__lte', 6)), name='check_stack_rank'),
        ),
    ]
