# Generated by Django 6.0.1 on 2026-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_stack_app', '0005_stack_check_stack_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order_in_deck',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order of the Card in the Deck', null=True, verbose_name='Orders in Deck'),
        ),
    ]
