# Generated by Django 6.0.1 on 2026-04-12 12:40

from django.db import migrations, models



def initialize_bots(apps, schema_editor) -> None:
    BotModel = apps.get_model("blind_stack_app", "Bot")
    BotModel.objects.get_or_create(pk=1, username="Jean", is_unlocked=True),
    BotModel.objects.get_or_create(pk=2, username="Edmond", is_unlocked=True),
    BotModel.objects.get_or_create(pk=3, username="Albert", is_unlocked=True),



class Migration(migrations.Migration):

    dependencies = [
        ('blind_stack_app', '0006_card_order_in_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Pseudo', max_length=30, verbose_name='Pseudos')),
                ('is_unlocked', models.BooleanField(default=False, help_text='Is unlocked ?', verbose_name='Is unlocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
            },
        ),
        migrations.RunPython(initialize_bots, migrations.RunPython.noop),
    ]
