# Generated by Django 6.0.1 on 2026-04-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_stack_app', '0007_bot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gameround',
            name='unique_players_in_game_round',
        ),
        migrations.AlterField(
            model_name='gameround',
            name='player_2',
            field=models.ForeignKey(help_text='Player Two of the GameRound (Bot)', on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_two', to='blind_stack_app.bot', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='player_3',
            field=models.ForeignKey(help_text='Player Three of the GameRound (Bot)', on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_three', to='blind_stack_app.bot', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='player_4',
            field=models.ForeignKey(blank=True, help_text='Player Four of the GameRound (Bot)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_four', to='blind_stack_app.bot', verbose_name='Players'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player_2', models.F('player_3')), _negated=True), models.Q(('player_4__isnull', True), models.Q(models.Q(('player_2', models.F('player_4')), _negated=True), models.Q(('player_3', models.F('player_4')), _negated=True)), _connector='OR')), name='unique_bots_in_game_round'),
        ),
    ]
