# Generated by Django 6.0.1 on 2026-04-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind_stack_app', '0008_remove_gameround_unique_players_in_game_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.RemoveConstraint(
            model_name='gameround',
            name='unique_bots_in_game_round',
        ),
        migrations.RemoveField(
            model_name='card',
            name='player',
        ),
        migrations.AddField(
            model_name='participant',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='Bots of the GameRound', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='blind_stack_app.bot', verbose_name='Bots'),
        ),
        migrations.AddField(
            model_name='participant',
            name='game_round',
            field=models.ForeignKey(blank=True, help_text='Participant of a GameRound', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='blind_stack_app.gameround', verbose_name='GameRounds'),
        ),
        migrations.AddField(
            model_name='participant',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Players of the GameRound', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='blind_stack_app.player', verbose_name='Players'),
        ),
        migrations.AddField(
            model_name='card',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='Participants of the GameRound', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='blind_stack_app.participant', verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='participant_1',
            field=models.ForeignKey(default=1, help_text='Participant One of the GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='game_as_participant_one', to='blind_stack_app.participant', verbose_name='Participants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameround',
            name='participant_2',
            field=models.ForeignKey(default=1, help_text='Participant Two of the GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='game_as_participant_two', to='blind_stack_app.participant', verbose_name='Participants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameround',
            name='participant_3',
            field=models.ForeignKey(default=1, help_text='Participant Three of the GameRound', on_delete=django.db.models.deletion.CASCADE, related_name='game_as_participant_three', to='blind_stack_app.participant', verbose_name='Participants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameround',
            name='participant_4',
            field=models.ForeignKey(blank=True, help_text='Participant Four of the GameRound', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_participant_four', to='blind_stack_app.participant', verbose_name='Participants'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participant_1', models.F('participant_2')), _negated=True), models.Q(('participant_1', models.F('participant_3')), _negated=True), models.Q(('participant_2', models.F('participant_3')), _negated=True), models.Q(('participant_4__isnull', True), models.Q(models.Q(('participant_2', models.F('participant_4')), _negated=True), models.Q(('participant_3', models.F('participant_4')), _negated=True)), _connector='OR')), name='unique_participants_in_game_round'),
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='player_4',
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('bot', 'game_round'), name='unique_bot_per_game_round'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('player', 'game_round'), name='unique_player_per_game_round'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('player__isnull', True), ('bot__isnull', True), _connector='XOR'), name='participant_is_player_or_bot_not_both'),
        ),
    ]
